// Auto-generated by VIP Connect Bot — do not edit manually
export const eventConfig = {
  // Core details
  city: "CITY_NAME",
  venue: "VENUE_NAME",
  venueAddress: "VENUE_ADDRESS",
  venueAddressFull: "VENUE_ADDRESS_FULL",
  date: "Month DD, YYYY",
  dateFull: "Day, Month DD",
  dateISO: "YYYY-MM-DD",
  calendarDateStart: "YYYYMMDDTHHMMSS",
  calendarDateEnd: "YYYYMMDDTHHMMSS",
  time: "7:00 PM",
  timezone: "TIMEZONE",
  timezoneAbbr: "TZ",
  capacity: 30,

  // Event naming
  eventTitle: "VIP Connect \u2014 CITY_NAME Leadership Dinner",
  eventSubtitle: "CITY_NAME Leadership Dinner",

  // Hero section
  heroImageUrl: "/venue/long-table.png",
  heroHeadline: "VIP Connect",
  heroSubheadline: "CITY_NAME Leadership Dinner",
  heroDescription:
    "An invitation-only gathering for senior leaders shaping the future of commerce and machine learning.",

  // Venue description
  venueDescription:
    "VENUE_DESCRIPTION — a short paragraph describing the venue, its character, and why it was chosen.",
  venueCapacityNote:
    "VENUE_CAPACITY_NOTE — describe the dining space, seating arrangement, and atmosphere.",
  venueDiningNote:
    "VENUE_DINING_NOTE — describe the menu style, wine, and service.",
  venueDirections:
    "VENUE_DIRECTIONS — address, nearest transport, and how guests will be greeted.",

  // Experience section copy
  experienceHeadline: "Thirty leaders.\nOne long table.\nNo slides.",
  experienceParagraphs: [
    "A closed-door, invitation-only evening designed for connection, not networking. The group is deliberately small. Senior enough to speak candidly, diverse enough to challenge each other\u2019s assumptions.",
    "The conversation centres on what machine learning is actually changing in commerce. Not the theory, but the reality. What\u2019s working, what\u2019s not, and what the next twelve months look like.",
    "VENUE_EXPERIENCE_PARAGRAPH — a sentence about the venue and the kind of evening it creates.",
  ],

  // Agenda
  agendaItems: [
    {
      time: "7:00 PM",
      title: "Arrival & Welcome Drinks",
      description:
        "Cocktails in the bar area. Introductions happen naturally when the setting is right and the group is deliberately small.",
    },
    {
      time: "7:30 PM",
      title: "Executive Session",
      description:
        "An unscripted discussion on the future of AI-driven performance, industry evolution, ecosystem collaboration, and what the next twelve months look like.",
    },
    {
      time: "7:45 PM",
      title: "Dinner",
      description:
        "AGENDA_DINNER_DESCRIPTION — describe the dining experience.",
    },
    {
      time: "10:00 PM",
      title: "Event Close",
      description: "An informal close as the evening winds down.",
    },
  ],

  // Agenda for calendar (short labels)
  agendaShort: [
    { time: "7:00 PM", label: "Arrival & welcome drinks" },
    { time: "7:30 PM", label: "Executive session" },
    { time: "7:45 PM", label: "Dinner" },
    { time: "10:00 PM", label: "Event close" },
  ],

  // FAQ
  faqItems: [
    {
      q: "What is Moloco VIP Connect?",
      a: "An invitation-only, in-person dinner designed for senior leaders across the commerce ecosystem, combining product innovation, industry insight, and high-quality peer discussion.",
    },
    {
      q: "Who is this event for?",
      a: "Senior executives and leadership in growth, UA, product, monetisation, and performance marketing. We keep the group to around 30 people. Small enough that everyone speaks, diverse enough that you\u2019ll hear something that changes how you think about a problem.",
    },
    {
      q: "Is this a public event / can I bring a +1?",
      a: "No. Attendance is by invitation only. Invitations may be shared with a relevant colleague or peer, subject to availability. Please check with us first before you share the RSVP link.",
    },
    {
      q: "What should I wear?",
      a: "Smart casual. Polished but comfortable. VENUE_NAME is VENUE_DRESS_CODE_NOTE.",
    },
    {
      q: "Is there a cost to attend?",
      a: "No. The evening is complimentary for confirmed guests. Dinner, drinks, and the full programme are on Moloco.",
    },
    {
      q: "What about dietary requirements?",
      a: "VENUE_NAME accommodates dietary needs: vegetarian, vegan, gluten-free, allergies. Note yours on the registration form and they\u2019ll take care of it.",
    },
  ],

  // URLs
  siteUrl: "https://DEPLOY_SLUG.vercel.app",
  mapsUrl: "https://maps.google.com/?q=VENUE_ADDRESS_ENCODED",

  // Slug
  slug: "DEPLOY_SLUG",

  // Calendar
  calendarTitle: "Moloco VIP Connect \u2014 CITY_NAME Leadership Dinner",
  calendarUidPrefix: "moloco-vip-connect-YYYY",
};
